// Auto-generated by tools/wp_generate_runtime_config.mjs from sites/bargig/site.profile.mjs.
// Do not edit this root runtime config directly; edit the site profile instead.
export default {
  flags: {},
  config: {
    cacheBudgetMb: 128,
    cacheMaxItems: 2000,
    debugBootTimings: false,
    branding: {
      storeId: 'bargig',
      displayName: 'רהיטי ברגיג',
    },
    storageNamespace: '',
    orderPdf: {
      templateUrl: 'order_template.pdf',
    },
    supabaseCloudSync: {
      url: 'https://paqzrxrvowwndevqptdk.supabase.co',
      anonKey:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcXpyeHJ2b3d3bmRldnFwdGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDExODcsImV4cCI6MjA4NTg3NzE4N30.hX4ciLINkSumjevU20rinv36wM7a72nZKr0TQYWs30o',
      storeId: 'bargig',
      gatewayFunction: 'wp-cloud-sync-room',
      publicRoom: 'public',
      roomParam: 'room',
      roomTokenParam: 'roomToken',
      shareBaseUrl: 'https://pro218.bargig-furniture.com/',
      pollMs: 1500,
      diagnostics: false,
      realtime: true,
      realtimeMode: 'broadcast',
      realtimeChannelPrefix: 'wp_cloud_sync',
      site2SketchInitialAutoLoad: true,
      site2SketchInitialMaxAgeHours: 12,
      showRoomWidget: true,
    },
  },
};
