// Closed runtime key registries for the public state mutation boundary.
// Keep runtime exports in parity with public_patch_keys.ts so bundlers that
// resolve explicit `.js` specifiers enforce the same canonical key surface.
export const PUBLIC_ROOT_PATCH_KEYS = ['ui', 'config', 'runtime', 'mode', 'meta'];

export const PUBLIC_UI_PATCH_KEYS = [
  'raw',
  'activeTab',
  'projectName',
  'selectedModelId',
  'width',
  'height',
  'depth',
  'doors',
  'color',
  'site2TabsGateOpen',
  'site2TabsGateUntil',
  'site2TabsGateBy',
  'doorStyle',
  'colorChoice',
  'frontColorShelfInheritanceMode',
  'customColor',
  'groovesEnabled',
  'splitDoors',
  'removeDoorsEnabled',
  'hasCornice',
  'corniceType',
  'currentCurtainChoice',
  'grooveManualEnabled',
  'currentGrooveDraftHeightCm',
  'currentGrooveDraftWidthCm',
  'currentGrooveOrientation',
  'currentMirrorDraftHeightCm',
  'currentMirrorDraftWidthCm',
  'currentLayoutType',
  'currentGridDivisions',
  'currentGridShelfVariant',
  'currentExtDrawerType',
  'currentExtDrawerCount',
  'internalDrawersEnabled',
  'handleControl',
  'currentHandleToolType',
  'currentHandleToolColor',
  'currentHandleToolEdgeVariant',
  'perCellGridMap',
  'activeGridCellId',
  'notesEnabled',
  'showHanger',
  'showContents',
  'showDimensions',
  'autosaveInfo',
  'noMainSketchRestoreSnapshot',
  'noMainSketchFreeExtrasSnapshot',
  'baseType',
  'shoeDrawerAutoBasePreviousType',
  'baseLegStyle',
  'baseLegColor',
  'baseLegPlatformMode',
  'baseLegPlatformSideMode',
  'baseLegPlatformSideOverhangCm',
  'baseLegPlatformFrontOverhangCm',
  'basePlinthHeightCm',
  'baseLegHeightCm',
  'baseLegWidthCm',
  'slidingTracksColor',
  'structureSelect',
  'singleDoorPos',
  'hingeDirection',
  'isChestMode',
  'chestCommodeEnabled',
  'chestCommodeMirrorWidthManual',
  'libraryUpperDoorsHidden',
  'cornerMode',
  'cornerSide',
  'cornerWidth',
  'cornerDoors',
  'cornerHeight',
  'cornerDepth',
  'cornerCabinetWallLenCm',
  'stackSplitEnabled',
  'stackSplitDecorativeSeparatorEnabled',
  'stackSplitDecorativeSeparatorSideOverhangCm',
  'stackSplitDecorativeSeparatorFrontOverhangCm',
  'cellDimsPanelOpen',
  'cellDimsHexPanelOpen',
  'sketchMode',
  'globalClickMode',
  'darkMode',
  'multiColorEnabled',
  'lightingControl',
  'currentFloorType',
  'lastSelectedFloorStyleIdByType',
  'lastSelectedWallColor',
  'lastLightPreset',
  'lightAmb',
  'lightDir',
  'lightX',
  'lightY',
  'lightZ',
  'orderPdfEditorOpen',
  'orderPdfEditorZoom',
  'orderPdfEditorDraft',
];

const PUBLIC_UI_PATCH_KEY_SET = new Set(PUBLIC_UI_PATCH_KEYS);

export function isPublicUiPatchKey(key) {
  return typeof key === 'string' && PUBLIC_UI_PATCH_KEY_SET.has(key);
}

export const PUBLIC_UI_RAW_PATCH_KEYS = [
  'width',
  'height',
  'depth',
  'doors',
  'structureSelect',
  'singleDoorPos',
  'chestDrawersCount',
  'chestCommodeMirrorHeightCm',
  'chestCommodeMirrorWidthCm',
  'chestCommodeMirrorWidthManual',
  'stackSplitLowerHeight',
  'stackSplitLowerDepth',
  'stackSplitLowerWidth',
  'stackSplitLowerDoors',
  'stackSplitLowerDepthManual',
  'stackSplitLowerWidthManual',
  'stackSplitLowerDoorsManual',
  'cornerWidth',
  'cornerHeight',
  'cornerDepth',
  'cornerDoors',
  'cellDimsWidth',
  'cellDimsHeight',
  'cellDimsDepth',
  'cellDimsHexMode',
  'cellDimsHexProtrusion',
  'cellDimsHexDoorWidth',
];

export const PUBLIC_RUNTIME_PATCH_KEYS = [
  'sketchMode',
  'globalClickMode',
  'doorsOpen',
  'doorsLastToggleTime',
  'drawersOpenId',
  'restoring',
  'systemReady',
  'roomDesignActive',
  'notesPicking',
  'failFast',
  'verboseConsoleErrors',
  'verboseConsoleErrorsDedupeMs',
  'debug',
  'paintColor',
  'handlesType',
  'interiorManualTool',
  'pendingGrooveLinesCountMap',
  'wardrobeWidthM',
  'wardrobeHeightM',
  'wardrobeDepthM',
  'wardrobeDoorsCount',
  'wardrobeTypeProfiles',
];

export const PUBLIC_CONFIG_PATCH_KEYS = [
  'modulesConfiguration',
  'stackSplitLowerModulesConfiguration',
  'savedColors',
  'colorSwatchesOrder',
  'savedNotes',
  'cornerConfiguration',
  'isLibraryMode',
  'wardrobeType',
  'globalHandleType',
  'isMultiColorMode',
  'showDimensions',
  'MIRROR_REFLECTOR_ENABLED',
  'isManualWidth',
  'boardMaterial',
  'doorMountMode',
  'drawerRunnerType',
  'overlayFrameThicknessCm',
  'overlayShelfThicknessCm',
  'insetFrameThicknessCm',
  'insetShelfThicknessCm',
  'customUploadedDataURL',
  'grooveLinesCount',
  'preChestState',
  'roomArchitecture',
];

export const PUBLIC_MODE_PATCH_KEYS = ['primary', 'opts'];
export const PUBLIC_META_PATCH_KEYS = ['dirty'];
