import type { Meters } from '../esm/shared/dimensions/units.js';
import {
  SKETCH_BOX_SHELL_GEOMETRY_POLICY,
  SKETCH_BOX_PLACEMENT_GEOMETRY_POLICY,
  SKETCH_BOX_SELECTOR_GEOMETRY_POLICY,
} from '../esm/shared/dimensions/sketch_box_geometry_policy.js';
import {
  SKETCH_BOX_DIVIDER_GEOMETRY_POLICY,
  SKETCH_BOX_DIVIDER_SNAP_POLICY,
  SKETCH_BOX_DIVIDER_REMOVE_HIT_POLICY,
} from '../esm/shared/dimensions/sketch_box_divider_policy.js';
import {
  SKETCH_BOX_DIMENSION_GROUPING_POLICY,
  SKETCH_BOX_DIMENSION_RENDER_POLICY,
} from '../esm/shared/dimensions/sketch_box_dimension_overlay_policy.js';
import {
  SKETCH_BOX_PREVIEW_CORE_POLICY,
  SKETCH_BOX_SHELF_PREVIEW_POLICY,
  SKETCH_BOX_ROD_PREVIEW_POLICY,
  SKETCH_BOX_STORAGE_PREVIEW_POLICY,
  SKETCH_BOX_DOOR_PREVIEW_POLICY,
  SKETCH_BOX_DRAWER_PREVIEW_POLICY,
  SKETCH_BOX_BOX_PREVIEW_POLICY,
  SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY,
  SKETCH_BOX_ADORNMENT_PREVIEW_POLICY,
} from '../esm/shared/dimensions/sketch_box_preview_policy.js';
import {
  SKETCH_BOX_FREE_VERTICAL_POLICY,
  SKETCH_BOX_FREE_WORKSPACE_CLAMP_POLICY,
  SKETCH_BOX_FREE_WALL_SNAP_POLICY,
  SKETCH_BOX_FREE_REMOVE_POLICY,
  SKETCH_BOX_FREE_ATTACH_CANDIDATE_POLICY,
  SKETCH_BOX_FREE_ATTACH_INTENT_POLICY,
  SKETCH_BOX_FREE_PLACEMENT_GAP_POLICY,
} from '../esm/shared/dimensions/sketch_box_free_placement_policy.js';

type Equal<Left, Right> =
  (<T>() => T extends Left ? 1 : 2) extends <T>() => T extends Right ? 1 : 2 ? true : false;
type Assert<Condition extends true> = Condition;
type IsPlainNumber<Value> = Value extends number ? (Value extends Meters ? false : true) : false;

export type SketchBoxPolicyTypeContracts = [
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.defaultWoodThicknessM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.minOuterWidthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.minOuterDepthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.minOuterHeightM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.minInnerDimensionM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.minInnerAdditiveClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.defaultOuterWidthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.defaultOuterDepthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.defaultOuterHeightM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELL_GEOMETRY_POLICY.maxOuterHeightM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_PLACEMENT_GEOMETRY_POLICY.placementClampPadMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_PLACEMENT_GEOMETRY_POLICY.placementClampPadMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_PLACEMENT_GEOMETRY_POLICY.placementClampPadWoodRatio>>,
  Assert<Equal<typeof SKETCH_BOX_PLACEMENT_GEOMETRY_POLICY.centerSnapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_PLACEMENT_GEOMETRY_POLICY.centerSnapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_PLACEMENT_GEOMETRY_POLICY.centerSnapWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_PLACEMENT_GEOMETRY_POLICY.centeredEpsilonM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SELECTOR_GEOMETRY_POLICY.selectorInnerMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SELECTOR_GEOMETRY_POLICY.selectorDepthClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SELECTOR_GEOMETRY_POLICY.selectorCenterZInsetM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_GEOMETRY_POLICY.fallbackWoodThicknessM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_GEOMETRY_POLICY.minInnerWidthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_GEOMETRY_POLICY.minInnerWithWoodClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_GEOMETRY_POLICY.dividerHalfMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_GEOMETRY_POLICY.segmentEdgeEpsilonM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_GEOMETRY_POLICY.pickEdgeEpsilonM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_GEOMETRY_POLICY.centeredEpsilonM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIVIDER_GEOMETRY_POLICY.defaultCenterNorm>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_SNAP_POLICY.centerSnapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_SNAP_POLICY.centerSnapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIVIDER_SNAP_POLICY.centerSnapWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_REMOVE_HIT_POLICY.removeHitMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIVIDER_REMOVE_HIT_POLICY.removeHitMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIVIDER_REMOVE_HIT_POLICY.removeHitWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_GROUPING_POLICY.groupAdjacentToleranceXMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_GROUPING_POLICY.groupAdjacentToleranceXMaxM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_GROUPING_POLICY.groupAdjacentToleranceYMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_GROUPING_POLICY.groupAdjacentToleranceYMaxM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_GROUPING_POLICY.groupSpanMergeToleranceMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_GROUPING_POLICY.groupSpanMergeToleranceMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.textScale>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleWidthLineYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleWidthLineYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleWidthLineYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleWidthTextYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleWidthTextYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleWidthTextYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleHeightLineGapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleHeightLineGapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleHeightLineGapWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleHeightTextXOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleHeightTextXOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleHeightTextXOffsetWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthLineGapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthLineGapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthLineGapWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthLineYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthLineYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthLineYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthTextXOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthTextXOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.singleDepthTextXOffsetWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthLineYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthLineYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthLineYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthTextYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthTextYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthTextYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthSegmentsYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthSegmentsYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupWidthSegmentsYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupSegmentTextYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupSegmentTextYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupSegmentTextYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupHeightLineGapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupHeightLineGapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupHeightLineGapWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupHeightTextXOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupHeightTextXOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupHeightTextXOffsetWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinHeightDeltaM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinHeightLineXOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinHeightLineXOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinHeightLineXOffsetWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinHeightTextXOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinHeightTextXOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinHeightTextXOffsetWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinHeightLabelShiftYM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthLineGapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthLineGapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthLineGapWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthLineYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthLineYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthLineYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthTextXOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthTextXOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupDepthTextXOffsetWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthDeltaM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthLineXOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthLineXOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthLineXOffsetWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthLineYOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthLineYOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthLineYOffsetHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthTextXOffsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthTextXOffsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DIMENSION_RENDER_POLICY.groupMinDepthTextXOffsetWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_PREVIEW_CORE_POLICY.minScaleM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_PREVIEW_CORE_POLICY.removeEpsShelfM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_PREVIEW_CORE_POLICY.removeEpsBoxM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfMinWidthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfHoverMinWidthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfBraceClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRegularClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveNoBoardToleranceMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveNoBoardToleranceMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveNoBoardToleranceStepRatio>>,
  Assert<Equal<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveBoardToleranceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveCornerDrawerToleranceExtraM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodRadiusM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodMinLengthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodWidthClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodPreviewHeightM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodPreviewDepthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodDefaultHeightM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodDefaultDepthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideDepthMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideDepthExtraM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideThicknessMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideThicknessMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideThicknessRatio>>,
  Assert<Equal<typeof SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideZOffsetM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_STORAGE_PREVIEW_POLICY.storageBarrierBackInsetM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_STORAGE_PREVIEW_POLICY.storageBarrierDepthClearanceMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_STORAGE_PREVIEW_POLICY.storageBarrierDepthClearanceMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_STORAGE_PREVIEW_POLICY.storageBarrierDepthClearanceRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorMinDimensionM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorEdgeEpsilonM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorInsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorInsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorInsetSizeRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairGapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairGapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairGapSizeRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairOuterInsetMinM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairOuterInsetSizeRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorThicknessMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorThicknessMaxM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorMinDepthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorBackClearanceMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorBackClearanceMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorBackClearanceDepthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorRemoveOffsetMinM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorRemoveOffsetWoodRatio>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.doorPreviewClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.frontOverlayWidthClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.frontOverlayHeightClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.segmentedDoorVisualClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.segmentedDoorMinHeightM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DOOR_PREVIEW_POLICY.segmentedDoorMinDimensionM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DRAWER_PREVIEW_POLICY.drawerPreviewThicknessM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_DRAWER_PREVIEW_POLICY.drawerPreviewZOffsetM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.boxFillThicknessMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.boxCenterMarkerThicknessMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.boxCenterMarkerThicknessMaxM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadXYMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadXYMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadXYWoodRatio>>,
  Assert<Equal<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadXYDefaultM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadZMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadZMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadZRatio>>,
  Assert<Equal<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementLabelZOffsetM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementHorizontalLabelOutsideGapM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementTextScaleMin>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementTextScaleDefault>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleDefaultX>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleDefaultY>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleCellX>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleCellY>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleNeighborX>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleNeighborY>>,
  Assert<Equal<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.slideClearanceMinM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.slideClearanceWoodRatio>>,
  Assert<Equal<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementZOffsetMinM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementZOffsetDepthRatio>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementTextScale>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceYOffsetM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceZInsetM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceWidthExtraM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceHeightM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceDepthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseDefaultHeightM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseZInsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseZInsetDepthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseLegWidthClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseWidthClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseDepthMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseLegDepthM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseDepthClearanceM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_VERTICAL_POLICY.verticalSlackDefaultM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_VERTICAL_POLICY.verticalSlackMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_VERTICAL_POLICY.verticalSlackMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_VERTICAL_POLICY.verticalSlackHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_VERTICAL_POLICY.roomFloorY, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_WORKSPACE_CLAMP_POLICY.workspaceClampPadMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_WORKSPACE_CLAMP_POLICY.workspaceClampPadMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_WORKSPACE_CLAMP_POLICY.workspaceClampPadHeightRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_WALL_SNAP_POLICY.wallSnapBandMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_WALL_SNAP_POLICY.wallSnapBandMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_WALL_SNAP_POLICY.wallSnapBandWidthRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_REMOVE_POLICY.removeInsetMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_REMOVE_POLICY.removeInsetMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_REMOVE_POLICY.removeInsetRatio>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_REMOVE_POLICY.removeInsetHalfRatioMax>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_REMOVE_POLICY.removeHalfMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_CANDIDATE_POLICY.attachPadMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_CANDIDATE_POLICY.attachPadMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_ATTACH_CANDIDATE_POLICY.attachPadSizeRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_CANDIDATE_POLICY.attachEdgeMinM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_ATTACH_CANDIDATE_POLICY.attachEdgeHalfRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentMinOverlapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentMinOverlapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentMinOverlapRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeBandMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeBandMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeBandRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeDominanceMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeDominanceMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeDominanceRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentOutsideBiasMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentOutsideBiasMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentOutsideBiasRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeBiasMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeBiasMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentEdgeBiasRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentScoreBiasMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentScoreBiasMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_ATTACH_INTENT_POLICY.attachIntentScoreBiasRatio>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_PLACEMENT_GAP_POLICY.placementGapDefaultM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_PLACEMENT_GAP_POLICY.placementGapMinM, Meters>>,
  Assert<Equal<typeof SKETCH_BOX_FREE_PLACEMENT_GAP_POLICY.placementGapMaxM, Meters>>,
  Assert<IsPlainNumber<typeof SKETCH_BOX_FREE_PLACEMENT_GAP_POLICY.placementGapRatio>>,
];
