import { meters } from './units.js';

export const BOOK_CONTENT_VISUAL_POLICY = Object.freeze({
  depthMarginM: meters(0.018),
  sideMarginM: meters(0.035),
  topSafetyM: meters(0.014),
  minHeightM: meters(0.07),
  minStackHeightM: meters(0.04),
  defaultMaxDepthM: meters(0.38),
  depthMaxM: meters(0.32),
  depthMinM: meters(0.12),
  depthRandomTrimRangeM: meters(0.045),
  depthViabilityMinM: meters(0.06),
  cursorEndGapM: meters(0.018),
  maxCount: 96,
  widthBaseM: meters(0.022),
  widthRandomRangeM: meters(0.026),
  setWidthBaseM: meters(0.026),
  setWidthRandomRangeM: meters(0.012),
  talmudSetWidthBaseM: meters(0.032),
  talmudSetWidthRandomRangeM: meters(0.01),
  narrowSetWidthBaseM: meters(0.019),
  narrowSetWidthRandomRangeM: meters(0.009),
  gapBaseM: meters(0.003),
  gapRandomRangeM: meters(0.006),
  setGapBaseM: meters(0.0016),
  setGapRandomRangeM: meters(0.0022),
  setTrailingGapM: meters(0.007),
  tiltZRangeRad: 0.045,
  setTiltZRangeRad: 0.018,
  edgeTiltZRangeRad: 0.04,
  angleCosMin: 0.001,
  heightBaseM: meters(0.16),
  heightRandomRangeM: meters(0.18),
  alignedHeightRatioBase: 0.78,
  alignedHeightRatioRange: 0.15,
  setHeightVariationM: meters(0.012),
  edgeHeightVariationM: meters(0.028),
  talmudHeightBoostM: meters(0.028),
  narrowSetHeightTrimM: meters(0.018),
  edgeZoneRatio: 0.14,
  edgeZoneMaxM: meters(0.13),
  setChance: 0.76,
  talmudSetChance: 0.34,
  narrowSetChance: 0.28,
  setMinVolumes: 5,
  setMaxVolumes: 14,
  shortRunMinVolumes: 2,
  shortRunMaxVolumes: 5,
  widthMinM: meters(0.01),
  spineBandChance: 0.82,
  spineBandHeightM: meters(0.008),
  spineBandThicknessM: meters(0.003),
  spineBandWidthInsetRatio: 0.18,
  spineBandYOffsetRatioA: 0.22,
  spineBandYOffsetRatioB: -0.18,
  stackChance: 0.08,
  stackLookaheadM: meters(0.04),
  stackMaxItems: 2,
  stackWidthBaseM: meters(0.07),
  stackWidthRandomRangeM: meters(0.035),
  stackTrailingGapM: meters(0.012),
  stackWidthMinM: meters(0.035),
  stackHeightBaseM: meters(0.04),
  stackHeightRandomRangeM: meters(0.018),
  stackDepthScaleBase: 0.92,
  stackDepthScaleRange: 0.08,
  stackXOffsetM: meters(0.014),
  stackCursorAdvanceM: meters(0.035),
  stackTiltYRangeRad: 0.04,
});

export const FOLDED_CLOTHES_VISUAL_POLICY = Object.freeze({
  defaultMaxHeightM: meters(0.5),
  baseItemDepthM: meters(0.36),
  depthMarginM: meters(0.015),
  minItemDepthM: meters(0.12),
  zSpreadMaxM: meters(0.015),
  zSpreadRatio: 0.35,
  itemHeightM: meters(0.025),
  heightHeadroomM: meters(0.03),
  stackPitchM: meters(0.3),
  stackXInsetM: meters(0.15),
  randomItemsRange: 4,
  stackBaseItems: 4,
  minHeightForSingleItemM: meters(0.06),
  itemWidthM: meters(0.26),
  cornerRadiusM: meters(0.008),
  randomOffsetXM: meters(0.015),
  rotationYRangeRad: 0.08,
});

export const HANGER_VISUAL_POLICY = Object.freeze({
  hookRadiusM: meters(0.02),
  hookTubeRadiusM: meters(0.0025),
  hookRadialSegments: 8,
  hookTubularSegments: 16,
  hookArcMultiplier: 1.5,
  hookYOffsetM: meters(0.045),
  stemRadiusM: meters(0.0025),
  stemHeightM: meters(0.04),
  stemYOffsetM: meters(0.02),
  halfWidthM: meters(0.22),
  shoulderHeightM: meters(0.15),
  centerHeightM: meters(0.015),
  bottomNeckYM: meters(0.002),
  shoulderCurveLiftM: meters(0.01),
  shoulderDropM: meters(0.015),
  bodyDepthM: meters(0.012),
  bevelThicknessM: meters(0.002),
  bevelSizeM: meters(0.002),
  bodyBackOffsetM: meters(0.006),
  barRadiusM: meters(0.009),
  barLengthHalfWidthMultiplier: 1.8,
  barYOffsetM: meters(0.01),
  moduleWidthClearanceM: meters(0.05),
  rodYOffsetM: meters(0.055),
  rotationYDivisor: 8,
});

export const HANGING_CLOTHES_VISUAL_POLICY = Object.freeze({
  minAvailableHeightM: meters(0.5),
  spacingM: meters(0.04),
  xOffsetM: meters(0.02),
  defaultDepthM: meters(0.45),
  framedDoorDepthM: meters(0.38),
  restrictedDepthMinM: meters(0.12),
  restrictedDepthDefaultM: meters(0.3),
  hangerRadiusM: meters(0.015),
  hangerTubeRadiusM: meters(0.002),
  hangerRadialSegments: 4,
  hangerTubularSegments: 12,
  hangerYOffsetM: meters(0.01),
  coatProbabilityThreshold: 0.7,
  coatHeightM: meters(1.1),
  shirtHeightM: meters(0.7),
  bottomClearanceM: meters(0.05),
  minRenderableHeightM: meters(0.1),
  clothWidthM: meters(0.03),
  clothYOffsetM: meters(0.02),
  clothRotationYRangeRad: 0.15,
});

export const CONTENT_VISUAL_POLICY = Object.freeze({
  books: BOOK_CONTENT_VISUAL_POLICY,
  foldedClothes: FOLDED_CLOTHES_VISUAL_POLICY,
  hanger: HANGER_VISUAL_POLICY,
  hangingClothes: HANGING_CLOTHES_VISUAL_POLICY,
});
