import { BASE_PLINTH_POLICY } from './base_plinth_policy.js';
import {
  INTERIOR_ROD_CONTENT_CLEARANCE_POLICY,
  INTERIOR_ROD_RENDER_POLICY,
  INTERIOR_SHELF_GEOMETRY_POLICY,
} from './interior_fittings_policy.js';
import { MATERIAL_THICKNESS_POLICY } from './material_thickness_policy.js';
import { meters } from './units.js';

export const SKETCH_BOX_PREVIEW_CORE_POLICY = Object.freeze({
  minScaleM: meters(0.0001),
  removeEpsShelfM: meters(0.02),
  removeEpsBoxM: meters(0.03),
});

export const SKETCH_BOX_SHELF_PREVIEW_POLICY = Object.freeze({
  shelfMinWidthM: meters(0.02),
  shelfHoverMinWidthM: meters(0.05),
  shelfBraceClearanceM: INTERIOR_SHELF_GEOMETRY_POLICY.braceWidthClearanceM,
  shelfRegularClearanceM: INTERIOR_SHELF_GEOMETRY_POLICY.regularWidthClearanceM,
  shelfRemoveNoBoardToleranceMinM: meters(0.018),
  shelfRemoveNoBoardToleranceMaxM: meters(0.03),
  shelfRemoveNoBoardToleranceStepRatio: 0.12,
  shelfRemoveBoardToleranceM: meters(0.035),
  shelfRemoveCornerDrawerToleranceExtraM: meters(0.006),
});

export const SKETCH_BOX_ROD_PREVIEW_POLICY = Object.freeze({
  rodRadiusM: INTERIOR_ROD_RENDER_POLICY.radiusM,
  rodMinLengthM: meters(0.05),
  rodWidthClearanceM: INTERIOR_ROD_CONTENT_CLEARANCE_POLICY.contentsWidthClearanceM,
  rodPreviewHeightM: meters(0.03),
  rodPreviewDepthM: meters(0.03),
  rodDefaultHeightM: meters(0.03),
  rodDefaultDepthM: meters(0.03),
  rodGuideDepthMinM: meters(0.006),
  rodGuideDepthExtraM: meters(0.004),
  rodGuideThicknessMinM: meters(0.006),
  rodGuideThicknessMaxM: meters(0.014),
  rodGuideThicknessRatio: 0.025,
  rodGuideZOffsetM: meters(0.001),
});

export const SKETCH_BOX_STORAGE_PREVIEW_POLICY = Object.freeze({
  storageBarrierBackInsetM: meters(0.009),
  storageBarrierDepthClearanceMinM: meters(0.02),
  storageBarrierDepthClearanceMaxM: meters(0.06),
  storageBarrierDepthClearanceRatio: 0.35,
});

export const SKETCH_BOX_DOOR_PREVIEW_POLICY = Object.freeze({
  doorMinDimensionM: meters(0.05),
  doorEdgeEpsilonM: meters(0.001),
  doorInsetMinM: meters(0.002),
  doorInsetMaxM: meters(0.006),
  doorInsetSizeRatio: 0.012,
  doorDoublePairGapMinM: meters(0.0008),
  doorDoublePairGapMaxM: meters(0.0018),
  doorDoublePairGapSizeRatio: 0.0045,
  doorDoublePairOuterInsetMinM: meters(0.0012),
  doorDoublePairOuterInsetSizeRatio: 0.0075,
  doorThicknessMinM: meters(0.016),
  doorThicknessMaxM: MATERIAL_THICKNESS_POLICY.wood.thicknessM,
  doorMinDepthM: meters(0.0001),
  doorBackClearanceMinM: meters(0.0008),
  doorBackClearanceMaxM: meters(0.0015),
  doorBackClearanceDepthRatio: 0.1,
  doorRemoveOffsetMinM: meters(0.002),
  doorRemoveOffsetWoodRatio: 0.12,
  doorPreviewClearanceM: meters(0.004),
  frontOverlayWidthClearanceM: meters(0.004),
  frontOverlayHeightClearanceM: meters(0.004),
  segmentedDoorVisualClearanceM: meters(0.004),
  segmentedDoorMinHeightM: meters(0.012),
  segmentedDoorMinDimensionM: meters(0.02),
});

export const SKETCH_BOX_DRAWER_PREVIEW_POLICY = Object.freeze({
  drawerPreviewThicknessM: meters(0.02),
  drawerPreviewZOffsetM: meters(0.001),
});

export const SKETCH_BOX_BOX_PREVIEW_POLICY = Object.freeze({
  boxFillThicknessMinM: meters(0.004),
  boxCenterMarkerThicknessMinM: meters(0.004),
  boxCenterMarkerThicknessMaxM: meters(0.012),
  objectBoxPadXYMinM: meters(0.0015),
  objectBoxPadXYMaxM: meters(0.004),
  objectBoxPadXYWoodRatio: 0.12,
  objectBoxPadXYDefaultM: meters(0.002),
  objectBoxPadZMinM: meters(0.0005),
  objectBoxPadZMaxM: meters(0.002),
  objectBoxPadZRatio: 0.5,
});

export const SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY = Object.freeze({
  measurementLabelZOffsetM: meters(0.0035),
  measurementHorizontalLabelOutsideGapM: meters(0.012),
  measurementTextScaleMin: 0.55,
  measurementTextScaleDefault: 0.9,
  measurementScaleDefaultX: 0.6,
  measurementScaleDefaultY: 0.3,
  measurementScaleCellX: 0.48,
  measurementScaleCellY: 0.24,
  measurementScaleNeighborX: 0.45,
  measurementScaleNeighborY: 0.225,
  slideClearanceMinM: meters(0.001),
  slideClearanceWoodRatio: 0.5,
  measurementZOffsetMinM: meters(0.004),
  measurementZOffsetDepthRatio: 0.08,
  measurementTextScale: 0.82,
});

export const SKETCH_BOX_ADORNMENT_PREVIEW_POLICY = Object.freeze({
  adornmentCorniceYOffsetM: meters(0.035),
  adornmentCorniceZInsetM: meters(0.012),
  adornmentCorniceWidthExtraM: meters(0.02),
  adornmentCorniceHeightM: meters(0.07),
  adornmentCorniceDepthM: meters(0.03),
  adornmentBaseDefaultHeightM: BASE_PLINTH_POLICY.heightM,
  adornmentBaseZInsetMaxM: meters(0.02),
  adornmentBaseZInsetDepthRatio: 0.15,
  adornmentBaseLegWidthClearanceM: meters(0.08),
  adornmentBaseWidthClearanceM: meters(0.04),
  adornmentBaseDepthMinM: MATERIAL_THICKNESS_POLICY.wood.thicknessM,
  adornmentBaseLegDepthM: meters(0.04),
  adornmentBaseDepthClearanceM: meters(0.05),
});

export const SKETCH_BOX_PREVIEW_POLICY = Object.freeze({
  minScaleM: SKETCH_BOX_PREVIEW_CORE_POLICY.minScaleM,
  removeEpsShelfM: SKETCH_BOX_PREVIEW_CORE_POLICY.removeEpsShelfM,
  removeEpsBoxM: SKETCH_BOX_PREVIEW_CORE_POLICY.removeEpsBoxM,
  shelfMinWidthM: SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfMinWidthM,
  shelfHoverMinWidthM: SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfHoverMinWidthM,
  shelfBraceClearanceM: SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfBraceClearanceM,
  shelfRegularClearanceM: SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRegularClearanceM,
  rodRadiusM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodRadiusM,
  rodMinLengthM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodMinLengthM,
  rodWidthClearanceM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodWidthClearanceM,
  rodPreviewHeightM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodPreviewHeightM,
  rodPreviewDepthM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodPreviewDepthM,
  shelfRemoveNoBoardToleranceMinM: SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveNoBoardToleranceMinM,
  shelfRemoveNoBoardToleranceMaxM: SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveNoBoardToleranceMaxM,
  shelfRemoveNoBoardToleranceStepRatio: SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveNoBoardToleranceStepRatio,
  shelfRemoveBoardToleranceM: SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveBoardToleranceM,
  shelfRemoveCornerDrawerToleranceExtraM:
    SKETCH_BOX_SHELF_PREVIEW_POLICY.shelfRemoveCornerDrawerToleranceExtraM,
  storageBarrierBackInsetM: SKETCH_BOX_STORAGE_PREVIEW_POLICY.storageBarrierBackInsetM,
  storageBarrierDepthClearanceMinM: SKETCH_BOX_STORAGE_PREVIEW_POLICY.storageBarrierDepthClearanceMinM,
  storageBarrierDepthClearanceMaxM: SKETCH_BOX_STORAGE_PREVIEW_POLICY.storageBarrierDepthClearanceMaxM,
  storageBarrierDepthClearanceRatio: SKETCH_BOX_STORAGE_PREVIEW_POLICY.storageBarrierDepthClearanceRatio,
  doorMinDimensionM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorMinDimensionM,
  doorEdgeEpsilonM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorEdgeEpsilonM,
  doorInsetMinM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorInsetMinM,
  doorInsetMaxM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorInsetMaxM,
  doorInsetSizeRatio: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorInsetSizeRatio,
  doorDoublePairGapMinM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairGapMinM,
  doorDoublePairGapMaxM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairGapMaxM,
  doorDoublePairGapSizeRatio: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairGapSizeRatio,
  doorDoublePairOuterInsetMinM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairOuterInsetMinM,
  doorDoublePairOuterInsetSizeRatio: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorDoublePairOuterInsetSizeRatio,
  doorThicknessMinM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorThicknessMinM,
  doorThicknessMaxM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorThicknessMaxM,
  doorMinDepthM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorMinDepthM,
  doorBackClearanceMinM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorBackClearanceMinM,
  doorBackClearanceMaxM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorBackClearanceMaxM,
  doorBackClearanceDepthRatio: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorBackClearanceDepthRatio,
  doorRemoveOffsetMinM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorRemoveOffsetMinM,
  doorRemoveOffsetWoodRatio: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorRemoveOffsetWoodRatio,
  doorPreviewClearanceM: SKETCH_BOX_DOOR_PREVIEW_POLICY.doorPreviewClearanceM,
  frontOverlayWidthClearanceM: SKETCH_BOX_DOOR_PREVIEW_POLICY.frontOverlayWidthClearanceM,
  frontOverlayHeightClearanceM: SKETCH_BOX_DOOR_PREVIEW_POLICY.frontOverlayHeightClearanceM,
  segmentedDoorVisualClearanceM: SKETCH_BOX_DOOR_PREVIEW_POLICY.segmentedDoorVisualClearanceM,
  segmentedDoorMinHeightM: SKETCH_BOX_DOOR_PREVIEW_POLICY.segmentedDoorMinHeightM,
  segmentedDoorMinDimensionM: SKETCH_BOX_DOOR_PREVIEW_POLICY.segmentedDoorMinDimensionM,
  drawerPreviewThicknessM: SKETCH_BOX_DRAWER_PREVIEW_POLICY.drawerPreviewThicknessM,
  drawerPreviewZOffsetM: SKETCH_BOX_DRAWER_PREVIEW_POLICY.drawerPreviewZOffsetM,
  boxFillThicknessMinM: SKETCH_BOX_BOX_PREVIEW_POLICY.boxFillThicknessMinM,
  boxCenterMarkerThicknessMinM: SKETCH_BOX_BOX_PREVIEW_POLICY.boxCenterMarkerThicknessMinM,
  boxCenterMarkerThicknessMaxM: SKETCH_BOX_BOX_PREVIEW_POLICY.boxCenterMarkerThicknessMaxM,
  rodDefaultHeightM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodDefaultHeightM,
  rodDefaultDepthM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodDefaultDepthM,
  rodGuideDepthMinM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideDepthMinM,
  rodGuideDepthExtraM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideDepthExtraM,
  rodGuideThicknessMinM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideThicknessMinM,
  rodGuideThicknessMaxM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideThicknessMaxM,
  rodGuideThicknessRatio: SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideThicknessRatio,
  rodGuideZOffsetM: SKETCH_BOX_ROD_PREVIEW_POLICY.rodGuideZOffsetM,
  objectBoxPadXYMinM: SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadXYMinM,
  objectBoxPadXYMaxM: SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadXYMaxM,
  objectBoxPadXYWoodRatio: SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadXYWoodRatio,
  objectBoxPadXYDefaultM: SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadXYDefaultM,
  objectBoxPadZMinM: SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadZMinM,
  objectBoxPadZMaxM: SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadZMaxM,
  objectBoxPadZRatio: SKETCH_BOX_BOX_PREVIEW_POLICY.objectBoxPadZRatio,
  measurementLabelZOffsetM: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementLabelZOffsetM,
  measurementHorizontalLabelOutsideGapM:
    SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementHorizontalLabelOutsideGapM,
  measurementTextScaleMin: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementTextScaleMin,
  measurementTextScaleDefault: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementTextScaleDefault,
  measurementScaleDefaultX: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleDefaultX,
  measurementScaleDefaultY: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleDefaultY,
  measurementScaleCellX: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleCellX,
  measurementScaleCellY: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleCellY,
  measurementScaleNeighborX: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleNeighborX,
  measurementScaleNeighborY: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementScaleNeighborY,
  slideClearanceMinM: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.slideClearanceMinM,
  slideClearanceWoodRatio: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.slideClearanceWoodRatio,
  measurementZOffsetMinM: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementZOffsetMinM,
  measurementZOffsetDepthRatio: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementZOffsetDepthRatio,
  measurementTextScale: SKETCH_BOX_MEASUREMENT_PREVIEW_POLICY.measurementTextScale,
  adornmentCorniceYOffsetM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceYOffsetM,
  adornmentCorniceZInsetM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceZInsetM,
  adornmentCorniceWidthExtraM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceWidthExtraM,
  adornmentCorniceHeightM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceHeightM,
  adornmentCorniceDepthM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentCorniceDepthM,
  adornmentBaseDefaultHeightM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseDefaultHeightM,
  adornmentBaseZInsetMaxM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseZInsetMaxM,
  adornmentBaseZInsetDepthRatio: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseZInsetDepthRatio,
  adornmentBaseLegWidthClearanceM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseLegWidthClearanceM,
  adornmentBaseWidthClearanceM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseWidthClearanceM,
  adornmentBaseDepthMinM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseDepthMinM,
  adornmentBaseLegDepthM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseLegDepthM,
  adornmentBaseDepthClearanceM: SKETCH_BOX_ADORNMENT_PREVIEW_POLICY.adornmentBaseDepthClearanceM,
});
