export type { DoorRemovalModeSnapshot, DoorRemovalUiSnapshot } from './internal/removal.js';
export { isRemoveDoorModeFromSnapshot, resolveRemoveDoorsEnabledFromSnapshots } from './internal/removal.js';

export type { DoorStyleOverrideValue } from './internal/style.js';
export {
  DOOR_STYLE_OVERRIDE_PAINT_PREFIX,
  GLASS_FRAME_STYLE_PAINT_PREFIX,
  encodeDoorStyleOverridePaintToken,
  encodeGlassFrameStylePaintToken,
  isDoorStyleOverridePaintToken,
  isDoorStyleOverrideValue,
  isGlassPaintSelection,
  normalizeDoorStyleOverrideValue,
  parseDoorStyleOverridePaintToken,
  parseGlassFrameStylePaintToken,
  readDoorStyleMap,
  resolveDoorStyleOverrideValue,
  resolveEffectiveDoorStyle,
  resolveGlassFrameStylePaintSelection,
} from './internal/style.js';

export type {
  DoorTrimAxis,
  DoorTrimCenterFromLocalArgs,
  DoorTrimColor,
  DoorTrimEntry,
  DoorTrimFindMatchArgs,
  DoorTrimMap,
  DoorTrimMatch,
  DoorTrimMirrorPlacementArgs,
  DoorTrimPlacementArgs,
  DoorTrimRect,
  DoorTrimSnappedCenterFromLocalArgs,
  DoorTrimSpan,
  DoorTrimSurfaceInfo,
  DoorTrimSurfacePlane,
  ResolvedDoorTrimPlacement,
} from './internal/trim.js';
export {
  CABINET_BODY_DOOR_TRIM_SURFACE_PARTS,
  DEFAULT_DOOR_TRIM_AXIS,
  DEFAULT_DOOR_TRIM_CENTER_NORM,
  DEFAULT_DOOR_TRIM_COLOR,
  DEFAULT_DOOR_TRIM_CROSS_SIZE_CM,
  DEFAULT_DOOR_TRIM_DEPTH_M,
  DEFAULT_DOOR_TRIM_SPAN,
  DEFAULT_DOOR_TRIM_THICKNESS_M,
  DOOR_TRIM_AXES,
  DOOR_TRIM_CENTER_SNAP_NORM_THRESHOLD,
  DOOR_TRIM_COLORS,
  DOOR_TRIM_MIRROR_EDGE_GAP_M,
  DOOR_TRIM_MIRROR_SNAP_ZONE_M,
  DOOR_TRIM_SPANS,
  MAX_DOOR_TRIM_CROSS_SIZE_CM,
  MAX_DOOR_TRIM_CUSTOM_CM,
  MIN_DOOR_TRIM_CROSS_SIZE_CM,
  MIN_DOOR_TRIM_CUSTOM_CM,
  MIN_DOOR_TRIM_SPAN_M,
  buildDoorTrimCenterFromLocal,
  buildDoorTrimCenterNormFromResolvedCenter,
  buildDoorTrimRectFromPlacement,
  buildDoorTrimSurfaceUserData,
  buildSnappedDoorTrimCenterFromLocal,
  clampDoorTrimCenterWithinDoor,
  clampDoorTrimNumber,
  cloneDoorTrimList,
  createDoorTrimEntry,
  findDoorTrimMatchInRect,
  isCabinetBodyDoorTrimSurfacePartId,
  isDoorTrimRecord,
  mapDoorTrimSurfaceLocalPoint,
  mapDoorTrimSurfaceLogicalToLocalPoint,
  normalizeDoorTrimAxis,
  normalizeDoorTrimCenterNorm,
  normalizeDoorTrimColor,
  normalizeDoorTrimCrossSizeCm,
  normalizeDoorTrimCustomSizeCm,
  normalizeDoorTrimSpan,
  readDoorTrimEntry,
  readDoorTrimFinite,
  readDoorTrimList,
  readDoorTrimListForPart,
  readDoorTrimMap,
  readDoorTrimSurfaceFaceCoordFromUserData,
  readDoorTrimSurfaceFaceSignFromUserData,
  readDoorTrimSurfacePlaneFromUserData,
  resolveCabinetBodyDoorTrimSurfaceInfo,
  resolveDoorTrimCenterPair,
  resolveDoorTrimFraction,
  resolveDoorTrimNormalizedCenter,
  resolveDoorTrimPlacement,
  resolveDoorTrimPlacementAvoidingMirror,
  resolveDoorTrimRemoveToleranceM,
  resolveDoorTrimSpanM,
} from './internal/trim.js';

export type {
  MirrorDraftInput,
  MirrorLayoutHitMatch,
  MirrorRect,
  PreparedMirrorRect,
  ResolvedMirrorPlacement,
  SnappedMirrorCenter,
} from './internal/mirror.js';
export {
  DEFAULT_CENTER_NORM,
  DEFAULT_FACE_SIGN,
  MIRROR_CENTER_SNAP_NORM_THRESHOLD,
  buildMirrorLayoutFromHit,
  buildSnappedMirrorCenterFromHit,
  cloneMirrorLayoutList,
  findMirrorLayoutMatchInRect,
  hasMirrorSurfaceOnFace,
  mirrorLayoutEquals,
  mirrorLayoutListEquals,
  normalizeMirrorDraftInput,
  normalizeMirrorFaceSign,
  readMirrorLayoutEntry,
  readMirrorLayoutFaceSign,
  readMirrorLayoutList,
  readMirrorLayoutListForPart,
  readMirrorLayoutMap,
  resolveMirrorPlacementInRect,
  resolveMirrorPlacementListInRect,
} from './internal/mirror.js';

export type { DoorVisualMapEntry } from './internal/visual_keys.js';
export {
  buildDoorVisualLookupKeys,
  hasAnyDoorVisualSegmentMapEntry,
  isDoorVisualSegmentPartId,
  readDoorVisualMapEntry,
  readDoorVisualMapValue,
  readDoorVisualMirrorLayout,
  readDoorVisualPrefixedMapEntry,
  readDoorVisualPrefixedOwnMapEntry,
  readDoorVisualSegmentBasePartId,
  readDoorVisualTextValue,
  stripDoorVisualSurfaceSuffix,
  toDoorStyleOverrideMapKey,
} from './internal/visual_keys.js';
