const freezeList = values => Object.freeze([...values]);

function contract(definition) {
  return Object.freeze({
    ...definition,
    scopes: freezeList(definition.scopes),
    supportingTests: freezeList(definition.supportingTests || []),
  });
}

function topology(definition) {
  return Object.freeze({
    ...definition,
    privateOwners: freezeList(definition.privateOwners),
    allowedImporters: freezeList(definition.allowedImporters || []),
    behaviorTests: freezeList(definition.behaviorTests),
  });
}

export const ARCHITECTURE_CONTRACT_REGISTRY = Object.freeze([
  contract({
    id: 'contract-registry',
    kind: 'control-plane',
    packageScript: 'check:contract-registry',
    owner: 'tools/wp_contract_registry_audit.mjs',
    scopes: ['canonical contract ownership', 'guardrail wiring'],
    supportingTests: ['tests/contract_registry_runtime.test.js'],
  }),
  contract({
    id: 'private-owner-boundaries',
    kind: 'topology',
    packageScript: 'check:private-owner-imports',
    owner: 'tools/wp_private_owner_import_boundary_audit.mjs',
    scopes: [
      'registered public facades',
      'private implementation owners',
      'reviewed identity-facade inventory',
    ],
    supportingTests: ['tests/private_owner_import_boundary_audit_runtime.test.js'],
  }),
  contract({
    id: 'project-migration-boundary',
    kind: 'source-guard',
    packageScript: 'check:project-migration-boundary',
    owner: 'tools/wp_project_migration_boundary_audit.mjs',
    scopes: ['project schema ingress', 'canonical config snapshots'],
    supportingTests: [
      'tests/project_migration_runtime_selector_hardening_runtime.test.ts',
      'tests/project_config_migration_replace_keys_runtime.test.ts',
    ],
  }),
  contract({
    id: 'runtime-selector-policy',
    kind: 'source-guard',
    packageScript: 'check:runtime-selector-policy',
    owner: 'tools/wp_runtime_selector_policy_audit.mjs',
    scopes: ['runtime selectors', 'canonical ui.raw selectors'],
    supportingTests: ['tests/runtime_selectors_normalization_runtime.test.ts'],
  }),
  contract({
    id: 'html-sinks',
    kind: 'source-guard',
    packageScript: 'check:html-sinks',
    owner: 'tools/wp_html_sink_audit.mjs',
    scopes: ['HTML sinks', 'sanitized rendering boundaries'],
  }),
  contract({
    id: 'builder-context-policy',
    kind: 'source-guard',
    packageScript: 'check:builder-context-policy',
    owner: 'tools/wp_builder_context_policy_audit.mjs',
    scopes: ['builder context', 'snapshot-bound build inputs'],
  }),
  contract({
    id: 'builder-pipeline',
    kind: 'source-guard',
    packageScript: 'check:builder-pipeline-contract',
    owner: 'tools/wp_builder_pipeline_contract.mjs',
    scopes: ['builder dependency resolver', 'build string normalization'],
    supportingTests: ['tests/builder_deps_resolver_runtime.test.js'],
  }),
  contract({
    id: 'features-public-api',
    kind: 'public-surface',
    packageScript: 'check:features-public-api',
    owner: 'tools/wp_features_public_api_contract.mjs',
    scopes: ['feature public manifest', 'retired source paths'],
    supportingTests: ['tests/features_public_api_type_hardening_contract.test.js'],
  }),
  contract({
    id: 'type-hardening',
    kind: 'source-guard',
    packageScript: 'check:type-hardening',
    owner: 'tools/wp_type_hardening_audit.mjs',
    scopes: ['unsafe casts', 'public/backend type boundaries'],
  }),
  contract({
    id: 'ui-option-buttons',
    kind: 'source-guard',
    packageScript: 'check:ui-option-buttons',
    owner: 'tools/wp_ui_option_button_contract.mjs',
    scopes: ['shared option primitives', 'migrated UI choices'],
  }),
  contract({
    id: 'ui-design-system',
    kind: 'source-guard',
    packageScript: 'check:ui-design-system',
    owner: 'tools/wp_ui_design_system_contract.mjs',
    scopes: ['shared React primitives', 'design-system consumers'],
  }),
  contract({
    id: 'ui-effect-cleanup',
    kind: 'source-guard',
    packageScript: 'check:ui-effect-cleanup',
    owner: 'tools/wp_ui_effect_cleanup_contract.mjs',
    scopes: ['idempotent DOM listener cleanup'],
  }),
  contract({
    id: 'canvas-hit-identity',
    kind: 'source-guard',
    packageScript: 'check:canvas-hit-identity',
    owner: 'tools/wp_canvas_hit_identity_contract.mjs',
    scopes: ['canonical hover/click hit identity'],
    supportingTests: ['tests/canvas_hit_identity_parity_runtime.test.js'],
  }),
  contract({
    id: 'canvas-hit-parity',
    kind: 'source-guard',
    packageScript: 'check:canvas-hit-parity',
    owner: 'tools/wp_canvas_hit_parity_contract.mjs',
    scopes: ['hover/click parity', 'paint and sketch identity routing'],
    supportingTests: ['tests/canvas_hit_identity_parity_runtime.test.js'],
  }),
  contract({
    id: 'cloud-sync-timers',
    kind: 'source-guard',
    packageScript: 'check:cloud-sync-timers',
    owner: 'tools/wp_cloud_sync_timer_contract.mjs',
    scopes: ['Cloud Sync timer ownership'],
  }),
  contract({
    id: 'cloud-sync-races',
    kind: 'source-guard',
    packageScript: 'check:cloud-sync-races',
    owner: 'tools/wp_cloud_sync_race_contract.mjs',
    scopes: ['Cloud Sync recovery', 'polling and realtime race handling'],
    supportingTests: [
      'tests/cloud_sync_pull_coalescer_runtime.test.ts',
      'tests/cloud_sync_lifecycle_refresh_async_recovery_runtime.test.ts',
    ],
  }),
  contract({
    id: 'cloud-sync-owner-decomposition',
    kind: 'source-guard',
    packageScript: 'check:cloud-sync-owner-decomposition',
    owner: 'tests/cloud_sync_owner_context_runtime_decomposition_contracts.test.js',
    scopes: [
      'Cloud Sync credential session ownership',
      'Cloud Sync row cache ownership',
      'Cloud Sync conflict journal ownership',
      'Cloud Sync gateway transport ownership',
      'Cloud Sync conflict resolution state machine',
      'Cloud Sync remote adoption coordination',
    ],
    supportingTests: ['tests/cloud_sync_owner_gateway_io_runtime.test.ts'],
  }),
  contract({
    id: 'performance-hotpaths',
    kind: 'source-guard',
    packageScript: 'check:perf-hotpaths',
    owner: 'tools/wp_perf_hotpath_contract.mjs',
    scopes: ['builder and scheduler hotpaths'],
    supportingTests: ['tests/perf_runtime_surface_runtime.test.ts'],
  }),
  contract({
    id: 'silent-catch-policy',
    kind: 'source-guard',
    packageScript: 'check:silent-catches',
    owner: 'tools/wp_silent_catch_policy_audit.mjs',
    scopes: ['production empty-catch ratchets', 'functional failure observability'],
    supportingTests: [
      'tests/silent_catch_policy_runtime.test.js',
      'tests/error_observability_core_runtime.test.ts',
    ],
  }),
  contract({
    id: 'canonical-domain-codecs',
    kind: 'source-guard',
    packageScript: 'check:domain-codecs',
    owner: 'tools/wp_domain_codec_contract.mjs',
    scopes: [
      'saved model persistence codec',
      'cloud collections persistence codec',
      'project config map codecs',
      'settings backup persistence codec',
      'project schema persistence codec',
    ],
    supportingTests: ['tests/canonical_domain_codecs_runtime.test.ts'],
  }),
  contract({
    id: 'test-portfolio',
    kind: 'portfolio',
    packageScript: 'check:test-portfolio',
    owner: 'tools/wp_test_portfolio_audit.mjs',
    scopes: ['test reachability', 'contract overlap', 'test-group ownership'],
    supportingTests: ['tests/contract_registry_runtime.test.js'],
  }),
]);

export const PRIVATE_OWNER_IMPORT_FAMILIES = Object.freeze([
  topology({
    id: 'runtime:perf-surface',
    publicFacade: 'esm/native/runtime/perf_runtime_surface.ts',
    privateOwners: [
      'esm/native/runtime/perf_runtime_core.ts',
      'esm/native/runtime/perf_runtime_state_fingerprint.ts',
      'esm/native/runtime/perf_runtime_debug_surfaces.ts',
      'esm/native/runtime/perf_runtime_surface_types.ts',
      'esm/native/runtime/perf_runtime_browser_observer.ts',
    ],
    behaviorTests: ['tests/perf_runtime_surface_runtime.test.ts'],
    justification: 'Stable runtime instrumentation surface over environment-specific collectors.',
  }),
  topology({
    id: 'builder:scheduler-debug-stats',
    publicFacade: 'esm/native/builder/scheduler_debug_stats.ts',
    privateOwners: [
      'esm/native/builder/scheduler_debug_stats_full.ts',
      'esm/native/builder/scheduler_debug_stats_prod.ts',
      'esm/native/builder/scheduler_debug_stats_reason_store.ts',
      'esm/native/builder/scheduler_debug_stats_signature_policy.ts',
      'esm/native/builder/scheduler_debug_stats_recorders.ts',
      'esm/native/builder/scheduler_debug_stats_budget.ts',
    ],
    allowedImporters: ['esm/native/builder/scheduler_runtime.ts'],
    behaviorTests: ['tests/builder_scheduler_runtime.test.ts'],
    justification: 'Build-mode alias boundary keeps production instrumentation minimal.',
  }),
  topology({
    id: 'builder:corner-connector-special',
    publicFacade: 'esm/native/builder/corner_connector_interior_special.ts',
    privateOwners: [
      'esm/native/builder/corner_connector_interior_special_types.ts',
      'esm/native/builder/corner_connector_interior_special_metrics.ts',
      'esm/native/builder/corner_connector_interior_special_geometry.ts',
      'esm/native/builder/corner_connector_interior_special_contents.ts',
      'esm/native/builder/corner_connector_interior_special_apply.ts',
    ],
    behaviorTests: ['tests/corner_connector_interior_policy_runtime.test.ts'],
    justification: 'Connector interior orchestration is a stable builder seam over focused geometry owners.',
  }),
  topology({
    id: 'kernel:domain-api-surface-shared',
    publicFacade: 'esm/native/kernel/domain_api_surface_sections_shared.ts',
    privateOwners: [
      'esm/native/kernel/domain_api_surface_sections_contracts.ts',
      'esm/native/kernel/domain_api_surface_sections_prefixed_maps.ts',
      'esm/native/kernel/domain_api_surface_sections_map_writes.ts',
      'esm/native/kernel/domain_api_surface_sections_removed_doors.ts',
    ],
    behaviorTests: ['tests/domain_api_surface_sections_runtime.test.ts'],
    justification: 'Domain surface sections share one kernel-owned map and contract boundary.',
  }),
  topology({
    id: 'services:models',
    publicFacade: 'esm/native/services/models.ts',
    privateOwners: [
      'esm/native/services/models_surface_install.ts',
      'esm/native/services/models_registry.ts',
      'esm/native/services/models_registry_contracts.ts',
      'esm/native/services/models_registry_loading.ts',
      'esm/native/services/models_registry_mutations.ts',
      'esm/native/services/models_registry_nonfatal.ts',
      'esm/native/services/models_registry_normalization.ts',
      'esm/native/services/models_registry_pdf_draft.ts',
      'esm/native/services/models_registry_runtime.ts',
      'esm/native/services/models_registry_shared.ts',
      'esm/native/services/models_registry_state.ts',
      'esm/native/services/models_registry_storage.ts',
      'esm/native/services/models_registry_storage_keys.ts',
      'esm/native/services/models_registry_storage_persistence.ts',
      'esm/native/services/models_registry_storage_state.ts',
      'esm/native/services/models_collections_transaction.ts',
      'esm/native/services/models_apply_ops.ts',
      'esm/native/services/models_apply_list_ops.ts',
      'esm/native/services/models_apply_load_ops.ts',
      'esm/native/services/models_apply_ops_shared.ts',
      'esm/native/services/models_apply_project.ts',
      'esm/native/services/models_apply_project_contracts.ts',
      'esm/native/services/models_apply_project_load.ts',
      'esm/native/services/models_apply_project_snapshot.ts',
      'esm/native/services/models_apply_snapshot_ops.ts',
      'esm/native/services/models_apply_state.ts',
      'esm/native/services/models_apply_transfer_ops.ts',
    ],
    allowedImporters: ['esm/native/services/api_services_project_surface.ts'],
    behaviorTests: ['tests/models_service_runtime.test.ts'],
    justification: 'Installed Models service methods require one stable service entry.',
  }),
  topology({
    id: 'data:preset-models',
    publicFacade: 'esm/native/data/preset_models.ts',
    privateOwners: ['esm/native/data/preset_models_data.ts'],
    behaviorTests: ['tests/preset_models_data_dimension_ownership_contract.test.js'],
    justification: 'Preset normalization is the supported data entry over the raw generated records.',
  }),
  topology({
    id: 'runtime:slice-write-dispatch',
    publicFacade: 'esm/native/runtime/slice_write_access_dispatch.ts',
    privateOwners: [
      'esm/native/runtime/slice_write_access_dispatch_order.ts',
      'esm/native/runtime/slice_write_access_dispatch_targets.ts',
      'esm/native/runtime/slice_write_access_plan.ts',
    ],
    allowedImporters: ['esm/native/runtime/slice_write_access_core.ts'],
    behaviorTests: ['tests/runtime_slice_write_router_runtime.test.ts'],
    justification: 'Canonical slice dispatch keeps ordering and target policy behind one runtime owner.',
  }),
  topology({
    id: 'ui:order-pdf-export-actions',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_export_actions.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_export_actions_callbacks.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_actions_interactive_blob.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_actions_ops.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_actions_pdfjs.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_actions_preview.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_actions_types.ts',
    ],
    behaviorTests: ['tests/order_pdf_overlay_export_ops_runtime.test.ts'],
    justification: 'React export callbacks consume one typed command surface.',
  }),
  topology({
    id: 'builder:scheduler-shared',
    publicFacade: 'esm/native/builder/scheduler_shared.ts',
    privateOwners: [
      'esm/native/builder/scheduler_shared_records.ts',
      'esm/native/builder/scheduler_shared_state.ts',
      'esm/native/builder/scheduler_shared_deps.ts',
      'esm/native/builder/scheduler_shared_environment.ts',
      'esm/native/builder/scheduler_shared_build_plan.ts',
      'esm/native/builder/scheduler_shared_timers.ts',
    ],
    behaviorTests: ['tests/builder_scheduler_runtime.test.ts'],
    justification: 'Scheduler state, dependencies, timers, and plans form one internal builder contract.',
  }),
  topology({
    id: 'ui:interior-tab-helpers',
    publicFacade: 'esm/native/ui/react/tabs/interior_tab_helpers.tsx',
    privateOwners: [
      'esm/native/ui/react/tabs/interior_tab_helpers_core.ts',
      'esm/native/ui/react/tabs/interior_tab_helpers_buttons.tsx',
      'esm/native/ui/react/tabs/interior_tab_helpers_sketch_tools.ts',
      'esm/native/ui/react/tabs/interior_tab_helpers_types.ts',
    ],
    behaviorTests: ['tests/interior_tab_sections_runtime.test.js'],
    justification: 'Interior tab consumers use one React helper surface.',
  }),
  topology({
    id: 'builder:room',
    publicFacade: 'esm/native/builder/room.ts',
    privateOwners: [
      'esm/native/builder/room_active_state.ts',
      'esm/native/builder/room_lifecycle.ts',
      'esm/native/builder/room_design_surface.ts',
    ],
    behaviorTests: ['tests/builder_room_runtime.test.ts'],
    justification: 'Room lifecycle and design publication are installed through one builder service surface.',
  }),
  topology({
    id: 'builder:preview-measurements',
    publicFacade: 'esm/native/builder/render_preview_sketch_measurements.ts',
    privateOwners: [
      'esm/native/builder/render_preview_sketch_measurements_apply.ts',
      'esm/native/builder/render_preview_sketch_measurements_input.ts',
      'esm/native/builder/render_preview_sketch_measurements_labels.ts',
      'esm/native/builder/render_preview_sketch_measurements_state.ts',
      'esm/native/builder/render_preview_sketch_measurements_types.ts',
    ],
    behaviorTests: ['tests/render_preview_sketch_measurements_runtime.test.ts'],
    justification: 'Preview measurement lifecycle needs one builder-owned entry.',
  }),
  topology({
    id: 'ui:order-pdf-sketch-toolbar',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_toolbar.tsx',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_toolbar_view.tsx',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_toolbar_palettes.tsx',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_toolbar_floating_palette.tsx',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_toolbar_freehand.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_toolbar_types.ts',
    ],
    behaviorTests: ['tests/order_pdf_overlay_sketch_panel_measurement_contracts.test.js'],
    justification: 'Toolbar view and palettes are private to the exported toolbar component.',
  }),
  topology({
    id: 'ui:order-pdf-text-layer-session',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_pointer_session_hooks.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_pointer_session_hooks_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_pointer_interaction_session_hooks.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_pointer_create_session_hooks.ts',
    ],
    behaviorTests: ['tests/order_pdf_overlay_sketch_text_box_create_interaction_runtime.test.ts'],
    justification: 'Pointer sessions expose one hook boundary over create and interaction state machines.',
  }),
  topology({
    id: 'ui:order-pdf-text-box-runtime',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_text_box_runtime.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_text_box_runtime_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_text_box_runtime_geometry.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_text_box_runtime_interaction.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_text_box_runtime_equality.ts',
    ],
    behaviorTests: ['tests/order_pdf_overlay_sketch_text_box_interaction_preview_runtime.test.ts'],
    justification: 'Text-box geometry and interaction policy are consumed through one runtime surface.',
  }),
  topology({
    id: 'ui:order-pdf-preview-controller',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_controller.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_controller_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_controller_viewport_state.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_controller_session.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_controller_refresh.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_controller_hook.ts',
    ],
    behaviorTests: ['tests/order_pdf_sketch_preview_session_runtime.test.ts'],
    justification: 'Preview URL lifecycle and refresh state are private to one controller hook.',
  }),
  topology({
    id: 'ui:order-pdf-sketch-canvas-runtime',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_canvas_runtime.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_canvas_runtime_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_canvas_runtime_equality.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_canvas_runtime_paint.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_canvas_runtime_resolve.ts',
    ],
    behaviorTests: ['tests/order_pdf_sketch_panel_canvas_runtime.test.ts'],
    justification: 'Canvas paint, equality, and resolution helpers are one sketch-panel runtime family.',
  }),
  topology({
    id: 'ui:order-pdf-sketch-panel-controller',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_controller.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_controller_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_controller_hook.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_controller_active_state.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_controller_state_hooks.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_controller_annotation_hooks.ts',
    ],
    behaviorTests: ['tests/order_pdf_sketch_panel_controller_runtime.test.ts'],
    justification: 'Panel state and annotation hooks are private to the controller surface.',
  }),
  topology({
    id: 'ui:order-pdf-card-text-layer',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_hooks.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_hooks_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_editor_hooks.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_palette_hooks.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_active_hooks.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_card_text_layer_hooks_hook.ts',
    ],
    behaviorTests: ['tests/order_pdf_overlay_sketch_card_contracts.test.js'],
    justification: 'Card text editing hooks expose one component-facing seam.',
  }),
  topology({
    id: 'ui:order-pdf-sketch-preview',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_draft.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_url_lifecycle.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_pdf_document.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_render_page.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_preview_build.ts',
    ],
    behaviorTests: ['tests/order_pdf_sketch_preview_session_runtime.test.ts'],
    justification: 'Preview document, render, and URL lifecycle stay behind one feature entry.',
  }),
  topology({
    id: 'ui:order-pdf-panel-measurement',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_measurement_hooks.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_measurement_hooks_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_measurement_observed_value.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_measurement_drawing_rect.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_measurement_placement.ts',
    ],
    behaviorTests: ['tests/order_pdf_overlay_sketch_panel_measurement_contracts.test.js'],
    justification: 'Measurement observation and placement are private to one hook surface.',
  }),
  topology({
    id: 'ui:order-pdf-sketch-panel',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel.tsx',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_view.tsx',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_header.tsx',
      'esm/native/ui/react/pdf/order_pdf_overlay_sketch_panel_cards.tsx',
    ],
    behaviorTests: ['tests/order_pdf_sketch_panel_runtime.test.ts'],
    justification: 'Sketch panel presentation stays behind one exported component.',
  }),
  topology({
    id: 'builder:carcass-cornice',
    publicFacade: 'esm/native/builder/render_carcass_ops_cornice.ts',
    privateOwners: [
      'esm/native/builder/render_carcass_ops_cornice_apply.ts',
      'esm/native/builder/render_carcass_ops_cornice_segments.ts',
      'esm/native/builder/render_carcass_ops_cornice_miter.ts',
      'esm/native/builder/render_carcass_ops_cornice_finalize.ts',
      'esm/native/builder/render_carcass_ops_cornice_types.ts',
    ],
    behaviorTests: ['tests/cornice_wave_individual_paint_runtime.test.ts'],
    justification: 'Carcass cornice rendering is invoked through one builder operation.',
  }),
  topology({
    id: 'builder:interior-sketch-shared',
    publicFacade: 'esm/native/builder/render_interior_sketch_shared.ts',
    privateOwners: [
      'esm/native/builder/render_interior_sketch_shared_types.ts',
      'esm/native/builder/render_interior_sketch_shared_records.ts',
      'esm/native/builder/render_interior_sketch_shared_numbers.ts',
      'esm/native/builder/render_interior_sketch_shared_external_drawers.ts',
      'esm/native/builder/render_interior_sketch_shared_box_doors.ts',
    ],
    behaviorTests: ['tests/render_interior_sketch_shared_external_drawers_runtime.test.ts'],
    justification: 'Interior sketch render owners share one typed record and numeric helper boundary.',
  }),
  topology({
    id: 'builder:preview-marker-ops',
    publicFacade: 'esm/native/builder/render_preview_marker_ops.ts',
    privateOwners: [
      'esm/native/builder/render_preview_marker_ops_factory.ts',
      'esm/native/builder/render_preview_marker_ops_types.ts',
      'esm/native/builder/render_preview_marker_ops_shared.ts',
      'esm/native/builder/render_preview_marker_ops_materials.ts',
      'esm/native/builder/render_preview_marker_ops_split.ts',
      'esm/native/builder/render_preview_marker_ops_door_action.ts',
      'esm/native/builder/render_preview_marker_ops_door_cut.ts',
    ],
    behaviorTests: ['tests/render_preview_measurement_contracts_runtime.test.ts'],
    justification: 'Preview marker creation is installed through one builder factory.',
  }),
  topology({
    id: 'builder:preview-sketch-ops',
    publicFacade: 'esm/native/builder/render_preview_sketch_ops.ts',
    privateOwners: [
      'esm/native/builder/render_preview_sketch_ops_factory.ts',
      'esm/native/builder/render_preview_sketch_ops_context.ts',
      'esm/native/builder/render_preview_sketch_ops_state.ts',
      'esm/native/builder/render_preview_sketch_ops_materials.ts',
      'esm/native/builder/render_preview_sketch_ops_meshes.ts',
      'esm/native/builder/render_preview_sketch_ops_apply.ts',
      'esm/native/builder/render_preview_sketch_ops_types.ts',
    ],
    behaviorTests: [
      'tests/render_preview_sketch_pipeline_linear_runtime.test.ts',
      'tests/render_preview_sketch_pipeline_box_content_runtime.test.ts',
    ],
    justification: 'Sketch placement preview state and rendering are installed as one builder operation.',
  }),
  topology({
    id: 'builder:interior-sketch-external-drawers',
    publicFacade: 'esm/native/builder/render_interior_sketch_drawers_external.ts',
    privateOwners: [
      'esm/native/builder/render_interior_sketch_drawers_external_apply.ts',
      'esm/native/builder/render_interior_sketch_drawers_external_context.ts',
      'esm/native/builder/render_interior_sketch_drawers_external_plan.ts',
      'esm/native/builder/render_interior_sketch_drawers_external_group.ts',
      'esm/native/builder/render_interior_sketch_drawers_external_visual.ts',
      'esm/native/builder/render_interior_sketch_drawers_external_box.ts',
      'esm/native/builder/render_interior_sketch_drawers_external_motion.ts',
      'esm/native/builder/render_interior_sketch_drawers_external_types.ts',
    ],
    behaviorTests: ['tests/external_drawer_ops_contracts_runtime.test.ts'],
    justification: 'External drawer sketch rendering exposes one apply operation.',
  }),
  topology({
    id: 'builder:interior-sketch-ops',
    publicFacade: 'esm/native/builder/render_interior_sketch_ops.ts',
    privateOwners: [
      'esm/native/builder/render_interior_sketch_ops_factory.ts',
      'esm/native/builder/render_interior_sketch_ops_context.ts',
      'esm/native/builder/render_interior_sketch_ops_input.ts',
      'esm/native/builder/render_interior_sketch_ops_dimensions.ts',
      'esm/native/builder/render_interior_sketch_ops_placement.ts',
      'esm/native/builder/render_interior_sketch_ops_boxes.ts',
      'esm/native/builder/render_interior_sketch_ops_extras.ts',
      'esm/native/builder/render_interior_sketch_ops_apply.ts',
      'esm/native/builder/render_interior_sketch_ops_types.ts',
    ],
    behaviorTests: ['tests/sketch_box_render_regression_guard.test.ts'],
    justification: 'Interior sketch render operations are installed through one builder factory.',
  }),
  topology({
    id: 'builder:sketch-box-shell',
    publicFacade: 'esm/native/builder/render_interior_sketch_boxes_shell.ts',
    privateOwners: [
      'esm/native/builder/render_interior_sketch_boxes_shell_apply.ts',
      'esm/native/builder/render_interior_sketch_boxes_shell_height.ts',
      'esm/native/builder/render_interior_sketch_boxes_shell_geometry.ts',
      'esm/native/builder/render_interior_sketch_boxes_shell_materials.ts',
      'esm/native/builder/render_interior_sketch_boxes_shell_frame.ts',
      'esm/native/builder/render_interior_sketch_boxes_shell_types.ts',
    ],
    behaviorTests: ['tests/render_interior_sketch_boxes_shell_apply_runtime.test.js'],
    justification: 'Sketch-box shell rendering exposes one apply operation.',
  }),
  topology({
    id: 'builder:sketch-box-front-drawers',
    publicFacade: 'esm/native/builder/render_interior_sketch_boxes_fronts_drawers.ts',
    privateOwners: [
      'esm/native/builder/render_interior_sketch_boxes_fronts_drawers_apply.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_drawers_context.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_drawers_plan.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_drawers_group.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_drawers_visual.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_drawers_box.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_drawers_motion.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_drawers_types.ts',
    ],
    allowedImporters: ['esm/native/builder/render_interior_sketch_boxes_fronts_door_handle_policy.ts'],
    behaviorTests: ['tests/sketch_box_drawers_and_cuts_runtime.test.ts'],
    justification: 'Sketch-box front drawer rendering exposes one apply operation.',
  }),
  topology({
    id: 'builder:sketch-box-static-contents',
    publicFacade: 'esm/native/builder/render_interior_sketch_boxes_contents_parts.ts',
    privateOwners: [
      'esm/native/builder/render_interior_sketch_boxes_contents_parts_apply.ts',
      'esm/native/builder/render_interior_sketch_boxes_contents_parts_materials.ts',
      'esm/native/builder/render_interior_sketch_boxes_contents_parts_dividers.ts',
      'esm/native/builder/render_interior_sketch_boxes_contents_parts_shelves.ts',
      'esm/native/builder/render_interior_sketch_boxes_contents_parts_barriers.ts',
      'esm/native/builder/render_interior_sketch_boxes_contents_parts_rods.ts',
      'esm/native/builder/render_interior_sketch_boxes_contents_parts_types.ts',
    ],
    behaviorTests: ['tests/render_interior_sketch_boxes_contents_parts_dividers_runtime.test.ts'],
    justification: 'Sketch-box static contents expose one render operation.',
  }),
  topology({
    id: 'features:part-identity',
    publicFacade: 'esm/native/features/part_identity/api.ts',
    privateOwners: [
      'esm/native/features/drawer_box_identity.ts',
      'esm/native/features/removable_parts.ts',
      'esm/native/features/shelf_part_identity.ts',
    ],
    behaviorTests: ['tests/removable_parts_frame_side_scope_runtime.test.ts'],
    justification: 'Cross-layer part identity consumers require one feature entry.',
  }),
  topology({
    id: 'features:door-authoring',
    publicFacade: 'esm/native/features/door_authoring/api.ts',
    privateOwners: [
      'esm/native/features/door_authoring/internal/removal.ts',
      'esm/native/features/door_authoring/internal/style.ts',
      'esm/native/features/door_authoring/internal/trim.ts',
      'esm/native/features/door_authoring/internal/trim_map.ts',
      'esm/native/features/door_authoring/internal/trim_placement.ts',
      'esm/native/features/door_authoring/internal/trim_placement_contracts.ts',
      'esm/native/features/door_authoring/internal/trim_placement_geometry.ts',
      'esm/native/features/door_authoring/internal/trim_placement_match.ts',
      'esm/native/features/door_authoring/internal/trim_placement_mirror.ts',
      'esm/native/features/door_authoring/internal/trim_shared.ts',
      'esm/native/features/door_authoring/internal/trim_surface_targets.ts',
      'esm/native/features/door_authoring/internal/visual_keys.ts',
      'esm/native/features/door_authoring/internal/mirror.ts',
      'esm/native/features/door_authoring/internal/mirror_geometry.ts',
      'esm/native/features/door_authoring/internal/mirror_lookup.ts',
      'esm/native/features/door_authoring/internal/groove_mirror_conflict.ts',
      'esm/native/features/door_authoring/internal/surface_layout_contracts.ts',
    ],
    behaviorTests: ['tests/canvas_picking_door_authoring_meta_runtime.test.ts'],
    justification: 'Door authoring is an explicit Feature Public API family.',
  }),
  topology({
    id: 'builder:sketch-box-door-visuals',
    publicFacade: 'esm/native/builder/render_interior_sketch_boxes_fronts_door_visuals.ts',
    privateOwners: [
      'esm/native/builder/render_interior_sketch_boxes_fronts_door_visual_materials.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_door_visual_routes.ts',
      'esm/native/builder/render_interior_sketch_boxes_fronts_door_visual_core.ts',
    ],
    behaviorTests: ['tests/sketch_box_door_visuals_runtime.test.ts'],
    justification: 'Door visual routing and materials stay behind one sketch-box orchestration seam.',
  }),
  topology({
    id: 'builder:drawer-shared-render-contract',
    publicFacade: 'esm/native/builder/render_drawer_ops_shared.ts',
    privateOwners: [
      'esm/native/builder/render_drawer_ops_shared_types.ts',
      'esm/native/builder/render_drawer_ops_shared_guards.ts',
      'esm/native/builder/render_drawer_ops_shared_readers.ts',
      'esm/native/builder/render_drawer_ops_shared_ops.ts',
      'esm/native/builder/render_drawer_ops_shared_visual_state.ts',
    ],
    behaviorTests: ['tests/render_drawer_contents_policy_runtime.test.ts'],
    justification: 'Drawer render consumers share one stable typed contract.',
  }),
  topology({
    id: 'ui:sketch-box-controls-runtime',
    publicFacade: 'esm/native/ui/react/tabs/interior_layout_sketch_box_controls_runtime.ts',
    privateOwners: [
      'esm/native/ui/react/tabs/interior_layout_sketch_box_controls_runtime_types.ts',
      'esm/native/ui/react/tabs/interior_layout_sketch_box_controls_runtime_sync.ts',
      'esm/native/ui/react/tabs/interior_layout_sketch_box_controls_runtime_dimensions.ts',
      'esm/native/ui/react/tabs/interior_layout_sketch_box_controls_runtime_panels.ts',
      'esm/native/ui/react/tabs/interior_layout_sketch_box_controls_runtime_base.ts',
      'esm/native/ui/react/tabs/interior_layout_sketch_box_controls_runtime_cornice.ts',
    ],
    behaviorTests: ['tests/sketch_box_doors_and_ui_guard.test.cjs'],
    justification: 'Sketch-box controls expose one component-facing mutation surface.',
  }),
  topology({
    id: 'runtime:ui-raw-selectors',
    publicFacade: 'esm/native/runtime/ui_raw_selectors.ts',
    privateOwners: [
      'esm/native/runtime/ui_raw_selectors_shared.ts',
      'esm/native/runtime/ui_raw_selectors_canonical.ts',
      'esm/native/runtime/ui_raw_selectors_store.ts',
    ],
    behaviorTests: ['tests/project_migration_runtime_selector_hardening_runtime.test.ts'],
    justification: 'Canonical ui.raw snapshot and store reads share one runtime entry.',
  }),
  topology({
    id: 'runtime:runtime-selectors',
    publicFacade: 'esm/native/runtime/runtime_selectors.ts',
    privateOwners: [
      'esm/native/runtime/runtime_selectors_shared.ts',
      'esm/native/runtime/runtime_selectors_normalizers.ts',
      'esm/native/runtime/runtime_selectors_snapshot.ts',
      'esm/native/runtime/runtime_selectors_store.ts',
    ],
    behaviorTests: ['tests/runtime_selectors_normalization_runtime.test.ts'],
    justification: 'Snapshot and store runtime reads share one normalized selector surface.',
  }),
  topology({
    id: 'ui:store-actions-ui',
    publicFacade: 'esm/native/ui/react/actions/store_actions_ui.ts',
    privateOwners: [
      'esm/native/ui/react/actions/store_actions_ui_contracts.ts',
      'esm/native/ui/react/actions/store_actions_ui_runtime.ts',
      'esm/native/ui/react/actions/store_actions_ui_writes.ts',
      'esm/native/ui/react/actions/store_actions_ui_project.ts',
      'esm/native/ui/react/actions/store_actions_ui_structure.ts',
      'esm/native/ui/react/actions/store_actions_ui_render.ts',
    ],
    behaviorTests: [
      'tests/store_actions_ui_runtime.test.ts',
      'tests/store_ui_action_capability_runtime.test.ts',
    ],
    justification:
      'React UI store actions keep AppContainer adaptation in one facade/runtime boundary while private write logic executes against narrow capabilities.',
  }),
  topology({
    id: 'services:viewer-measurement-tool',
    publicFacade: 'esm/native/services/viewer_measurement_tool.ts',
    privateOwners: [
      'esm/native/services/viewer_measurement_geometry_runtime.ts',
      'esm/native/services/viewer_measurement_tool_contracts.ts',
      'esm/native/services/viewer_measurement_tool_flow.ts',
      'esm/native/services/viewer_measurement_tool_geometry.ts',
      'esm/native/services/viewer_measurement_tool_point_geometry.ts',
      'esm/native/services/viewer_measurement_tool_point_resolution.ts',
      'esm/native/services/viewer_measurement_tool_resolution.ts',
      'esm/native/services/viewer_measurement_tool_runtime.ts',
      'esm/native/services/viewer_measurement_part_label.ts',
    ],
    behaviorTests: [
      'tests/viewer_measurement_tool_runtime.test.ts',
      'tests/viewer_measurement_tool_capability_runtime.test.ts',
    ],
    justification:
      'Viewer measurement lifecycle is a supported facade with private capability-flow/runtime owners.',
  }),
  topology({
    id: 'services:drawer-cross-family',
    publicFacade: 'esm/native/services/canvas_picking_drawer_cross_family.ts',
    privateOwners: [
      'esm/native/services/canvas_picking_drawer_cross_family_model.ts',
      'esm/native/services/canvas_picking_drawer_cross_family_hit_identity.ts',
      'esm/native/services/canvas_picking_drawer_cross_family_direct_hit.ts',
      'esm/native/services/canvas_picking_drawer_cross_family_preview.ts',
      'esm/native/services/canvas_picking_drawer_cross_family_remove_plan.ts',
    ],
    behaviorTests: ['tests/canvas_picking_drawer_cross_family_remove_plan_runtime.test.ts'],
    justification: 'Drawer hover/commit families share one cross-family service seam.',
  }),
  topology({
    id: 'ui:order-pdf-export-commands',
    publicFacade: 'esm/native/ui/react/pdf/order_pdf_overlay_export_commands.ts',
    privateOwners: [
      'esm/native/ui/react/pdf/order_pdf_overlay_export_commands_types.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_commands_errors.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_commands_load_pdf.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_commands_downloads.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_commands_gmail.ts',
      'esm/native/ui/react/pdf/order_pdf_overlay_export_commands_pdfjs.ts',
    ],
    behaviorTests: ['tests/order_pdf_overlay_export_commands_runtime.test.ts'],
    justification: 'Order PDF export flows require one typed UI command surface.',
  }),
]);

export const JUSTIFIED_ONE_LINE_FACADES = Object.freeze(
  [
    ['esm/entry_pro_start.ts', 'Browser entry naming boundary.'],
    ['esm/native/builder/render_carcass_ops_cornice.ts', 'Registered builder operation facade.'],
    ['esm/native/builder/render_interior_sketch_boxes_shell.ts', 'Registered builder operation facade.'],
    ['esm/native/builder/render_interior_sketch_drawers_external.ts', 'Registered builder operation facade.'],
    ['esm/native/builder/render_interior_sketch_ops.ts', 'Registered builder operation facade.'],
    ['esm/native/builder/render_preview_marker_ops.ts', 'Registered builder operation facade.'],
    ['esm/native/builder/render_preview_sketch_ops.ts', 'Registered builder operation facade.'],
    ['esm/native/builder/scheduler_debug_stats.ts', 'Build-mode alias boundary.'],
    ['esm/native/data/install.ts', 'Boot manifest entry.'],
    ['esm/native/io/project_file_ingress_command.ts', 'Project file ingress command boundary.'],
    [
      'esm/native/services/install.ts',
      'Supported Services installer entry listed by the public API contract.',
    ],
    ['esm/native/services/canvas_picking_generic_paint_hover.ts', 'Canvas hover use-case entry.'],
    [
      'esm/native/services/canvas_picking_sketch_free_surface_preview_target.ts',
      'Sketch preview target-scanning entry.',
    ],
    [
      'esm/native/services/cloud_sync_install_support_publication.ts',
      'Cloud Sync publication lifecycle entry.',
    ],
    ['esm/native/services/cloud_sync_panel_api_install_surface.ts', 'Cloud Sync panel installation entry.'],
    ['esm/native/ui/notes_export_render.ts', 'Notes export rendering entry.'],
  ].map(([path, reason]) => Object.freeze({ path, reason }))
);
