#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = process.cwd();
const importPattern = /(?:import|export)\s+(?:[^;'\"]*?\s+from\s+)?['\"]([^'\"]*\/features\/[^'\"]+)['\"]/gs;

function compareCodePoints(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function walk(dir, out = []) {
  let entries = [];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  entries.sort((left, right) => compareCodePoints(left.name, right.name));
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'dist') continue;
      walk(abs, out);
    } else if (/\.(?:ts|tsx|js|mjs)$/.test(entry.name)) {
      out.push(abs);
    }
  }
  return out;
}

function rel(projectRoot, file) {
  return path.relative(projectRoot, file).replace(/\\/g, '/');
}

function featureEntryFromSpecifier(specifier) {
  const marker = '/features/';
  const at = specifier.indexOf(marker);
  if (at < 0) return null;
  return specifier.slice(at + marker.length).replace(/\?.*$/, '');
}

function familyOf(entry) {
  if (entry.includes('/')) return entry.split('/')[0];
  return entry.replace(/\.js$/, '');
}

function buildMarkdownReport(result) {
  const lines = [];
  lines.push('# Features Public API Audit');
  lines.push('');
  lines.push('Generated by `tools/wp_features_public_api_contract.mjs`.');
  lines.push('');
  lines.push(`- Public entries: ${result.publicEntries.length}`);
  lines.push(`- Import sites outside \`features/\`: ${result.importSites.length}`);
  lines.push(`- Violations: ${result.violations.length}`);
  lines.push('');
  lines.push('## Public entries by family');
  lines.push('');
  for (const [family, entries] of Object.entries(result.byFamily).sort(([a], [b]) =>
    compareCodePoints(a, b)
  )) {
    lines.push(`### ${family}`);
    lines.push('');
    for (const entry of entries) lines.push(`- \`${entry}\``);
    lines.push('');
  }
  if (result.violations.length) {
    lines.push('## Violations');
    lines.push('');
    for (const violation of result.violations) lines.push(`- ${violation}`);
    lines.push('');
  }
  return lines.join('\n');
}

function resolveProjectPath(projectRoot, file) {
  return path.isAbsolute(file) ? file : path.join(projectRoot, file);
}

function ensureParentDir(file) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
}

function readTextIfExists(file) {
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
}

function normalizeLineEndings(text) {
  return String(text || '').replace(/\r\n/g, '\n');
}

function normalizeMarkdownArtifact(text) {
  return normalizeLineEndings(text)
    .split('\n')
    .map(line => line.replace(/[ \t]+$/g, ''))
    .join('\n')
    .replace(/\n+$/g, '');
}

function normalizeJsonForCompare(value) {
  if (Array.isArray(value)) return value.map(normalizeJsonForCompare);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value)
      .sort(([a], [b]) => compareCodePoints(a, b))
      .map(([key, entry]) => [key, normalizeJsonForCompare(entry)])
  );
}

function compareJsonArtifact({ file, expected }) {
  const actual = readTextIfExists(file);
  if (actual === null) return { file: rel(root, file), reason: 'missing' };
  try {
    const actualComparable = JSON.stringify(normalizeJsonForCompare(JSON.parse(actual)));
    const expectedComparable = JSON.stringify(normalizeJsonForCompare(expected));
    if (actualComparable === expectedComparable) return null;
    return { file: rel(root, file), reason: 'stale' };
  } catch {
    return { file: rel(root, file), reason: 'invalid-json' };
  }
}

function compareTextArtifact({ file, expected }) {
  const actual = readTextIfExists(file);
  if (actual === null) return { file: rel(root, file), reason: 'missing' };
  if (normalizeMarkdownArtifact(actual) === normalizeMarkdownArtifact(expected)) return null;
  return { file: rel(root, file), reason: 'stale' };
}

function checkDocsAreCurrent(result) {
  const expectedMarkdown = buildMarkdownReport(result);
  return [
    compareJsonArtifact({
      file: path.join(root, 'docs/features_public_api_audit.json'),
      expected: result,
    }),
    compareTextArtifact({
      file: path.join(root, 'docs/FEATURES_PUBLIC_API_AUDIT.md'),
      expected: expectedMarkdown,
    }),
  ].filter(Boolean);
}

export function runFeaturesPublicApiContract(projectRoot = root) {
  const manifest = readJson(path.join(projectRoot, 'tools/wp_features_public_api_manifest.json'));
  const publicEntries = Array.isArray(manifest.publicEntries) ? manifest.publicEntries : [];
  const allowed = new Set(publicEntries);
  const importSites = [];
  const violations = [];
  const byFamily = {};

  for (const entry of publicEntries) {
    const family = familyOf(entry);
    if (!byFamily[family]) byFamily[family] = [];
    byFamily[family].push(entry);
  }

  for (const file of walk(path.join(projectRoot, 'esm/native'))) {
    const fileRel = rel(projectRoot, file);
    if (fileRel.startsWith('esm/native/features/')) continue;
    const source = fs.readFileSync(file, 'utf8');
    importPattern.lastIndex = 0;
    for (const match of source.matchAll(importPattern)) {
      const entry = featureEntryFromSpecifier(match[1]);
      if (!entry) continue;
      importSites.push({ file: fileRel, entry });
      if (!allowed.has(entry)) {
        violations.push(`${fileRel} imports non-public feature entry ${entry}`);
      }
    }
  }

  importSites.sort((left, right) => compareCodePoints(left.file, right.file));
  violations.sort(compareCodePoints);

  return {
    ok: violations.length === 0,
    policy: manifest.policy || '',
    publicEntries,
    byFamily,
    importSites,
    violations,
  };
}

function parseArgs(argv) {
  const args = { jsonOut: '', mdOut: '', checkDocs: false };
  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--json-out') args.jsonOut = argv[++i] || '';
    else if (arg === '--md-out') args.mdOut = argv[++i] || '';
    else if (arg === '--check-docs') args.checkDocs = true;
  }
  return args;
}

function main() {
  const args = parseArgs(process.argv);
  const result = runFeaturesPublicApiContract(root);
  if (args.jsonOut) {
    const jsonOut = resolveProjectPath(root, args.jsonOut);
    ensureParentDir(jsonOut);
    fs.writeFileSync(jsonOut, `${JSON.stringify(result, null, 2)}\n`);
  }
  if (args.mdOut) {
    const mdOut = resolveProjectPath(root, args.mdOut);
    ensureParentDir(mdOut);
    fs.writeFileSync(mdOut, buildMarkdownReport(result));
  }
  const docDrift = args.checkDocs ? checkDocsAreCurrent(result) : [];
  if (docDrift.length) {
    console.error('[features-public-api] generated docs are stale');
    for (const drift of docDrift) console.error(`- ${drift.file}: ${drift.reason}`);
    process.exit(1);
  }
  if (!result.ok) {
    console.error('[features-public-api] FAILED');
    for (const violation of result.violations) console.error(`- ${violation}`);
    process.exit(1);
  }
  console.log(
    `[features-public-api] ok (${result.publicEntries.length} public entries, ${result.importSites.length} import sites)`
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
